SELECT
    b.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(b.PRICE * bs.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a
  ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES bs
  ON b.BOOK_ID = bs.BOOK_ID
WHERE bs.SALES_DATE >= '2022-01-01'
  AND bs.SALES_DATE <  '2022-02-01'
GROUP BY
    b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY
    b.AUTHOR_ID ASC, b.CATEGORY DESC;
