-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SUBSTR(I.SEX_UPON_INTAKE,1,1) = 'I' AND (SUBSTR(O.SEX_UPON_OUTCOME,1,1) = 'N' OR SUBSTR(O.SEX_UPON_OUTCOME,1,1) = 'S')
ORDER BY ANIMAL_ID ASC;