SELECT
    YEAR(o.SALES_DATE)  AS YEAR,
    MONTH(o.SALES_DATE) AS MONTH,
    COUNT(DISTINCT o.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT o.USER_ID) / (SELECT COUNT(*) 
                                     FROM USER_INFO 
                                     WHERE YEAR(JOINED) = 2021),
        1
    ) AS PURCHASED_RATIO
FROM ONLINE_SALE o
JOIN USER_INFO u
  ON u.USER_ID = o.USER_ID
WHERE YEAR(u.JOINED) = 2021
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE)
ORDER BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE);
