SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(O.AMOUNT * P.PRICE) AS TOTAL_REVENUE
FROM 
    FOOD_PRODUCT P
JOIN 
    FOOD_ORDER O
ON 
    P.PRODUCT_ID = O.PRODUCT_ID
WHERE 
    O.PRODUCE_DATE BETWEEN DATE '2022-05-01' AND DATE '2022-05-31'
GROUP BY 
    P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY 
    TOTAL_REVENUE DESC,
    P.PRODUCT_ID ASC;
