SELECT HOUR(A.DATETIME) AS HOUR, IFNULL(COUNT(A.DATETIME),0) AS COUNT
FROM ( SELECT 9 AS HOUR UNION ALL SELECT 10 AS HOUR UNION ALL SELECT 11 AS HOUR UNION ALL
      SELECT 12 AS HOUR UNION ALL SELECT 13 AS HOUR UNION ALL SELECT 14 AS HOUR UNION ALL
      SELECT 15 AS HOUR UNION ALL SELECT 16 AS HOUR UNION ALL SELECT 17 AS HOUR UNION ALL
      SELECT 18 AS HOUR UNION ALL SELECT 19 AS HOUR) H
LEFT JOIN ANIMAL_OUTS A
ON H.HOUR = HOUR(A.DATETIME)
GROUP BY H.HOUR
ORDER BY HOUR